//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int logID { get; set; }
        public Nullable<int> studentID { get; set; }
        public string dateTimeChanged { get; set; }
        public string dbUser { get; set; }
        public string oldLastName { get; set; }
        public string newLastName { get; set; }
        public string oldFirstName { get; set; }
        public string newFirstName { get; set; }
        public Nullable<int> oldMobile { get; set; }
        public Nullable<int> newMobile { get; set; }
    
        public virtual student student { get; set; }
    }
}
