//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarkRomigEntities1 : DbContext
    {
        public MarkRomigEntities1()
            : base("name=MarkRomigEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<cd> cds { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<interest> interests { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Procedure> Procedures { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<record> records { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<sale1> sales1 { get; set; }
        public virtual DbSet<special_passion> special_passion { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<TestTable> TestTables { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
    }
}
