//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int prodID { get; set; }
        public string prodName { get; set; }
        public Nullable<decimal> sellingPrice { get; set; }
        public Nullable<decimal> sales_ytd { get; set; }
    }
}
