//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale1
    {
        public System.DateTime dateOrdered { get; set; }
        public string recordID { get; set; }
        public int customerNumber { get; set; }
        public decimal price { get; set; }
        public string interestCode { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual record record { get; set; }
    }
}
