//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public System.DateTime dateOrdered { get; set; }
        public decimal price { get; set; }
        public string cdID { get; set; }
        public int clientNumber { get; set; }
        public string passionCode { get; set; }
    
        public virtual cd cd { get; set; }
        public virtual client client { get; set; }
    }
}
