//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int procedureID { get; set; }
        public string petName { get; set; }
        public decimal price { get; set; }
        public int ownerID { get; set; }
        public System.DateTime date { get; set; }
        public string notes { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
